---
# Ansible Galaxy requirements file
# Install roles and collections using: ansible-galaxy install -r requirements.yml

# Collections
collections:
  - name: community.general
    version: ">=8.0.0"
  
  - name: ansible.posix
    version: ">=1.5.0"

# Roles (examples - uncomment and modify as needed)
# roles:
#   - name: geerlingguy.docker
#     version: "7.0.1"
#   
#   - name: geerlingguy.security
#     version: "3.0.0"
