---
# Main inventory file for iotops
# This file defines all hosts and groups for your infrastructure

all:
  children:
    # Production environment
    production:
      children:
        iot_devices:
          hosts:
            iot-device-01:
              ansible_host: 192.168.1.101
              device_type: sensor
            iot-device-02:
              ansible_host: 192.168.1.102
              device_type: actuator
        
        iot_gateways:
          hosts:
            iot-gateway-01:
              ansible_host: 192.168.1.10
              gateway_role: primary
        
        iot_servers:
          hosts:
            iot-server-01:
              ansible_host: 192.168.1.20
              server_role: application
    
    # Staging environment
    staging:
      children:
        iot_devices:
          hosts:
            iot-device-staging-01:
              ansible_host: 192.168.2.101
              device_type: sensor
        
        iot_gateways:
          hosts:
            iot-gateway-staging-01:
              ansible_host: 192.168.2.10
              gateway_role: primary
